@startuml

hide empty members
hide circle

skinparam minClassWidth 120


class \nDomain\n
class \nApplication\n
class \nInfrastructure\n
class \nUi\n

\nDomain\n --|> \nApplication\n
\nApplication\n --|> \nInfrastructure\n
\nInfrastructure\n --|> \nUi\n
@enduml
